[project]
name = "quatorch"
version = "0.1.2"
description = "Quaternion operations in pure PyTorch"
keywords = ["quaternion", "rotation", "3d", "orientation",  "pytorch"]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "torch>=1.7.0",
]

authors = [
  {name = "Lucas N. Egidio", email = "lucasegidio1@gmail.com"},
]
maintainers = [
  {name = "Lucas N. Egidio", email = "lucasegidio1@gmail.com"},
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",

  # TODO verify "License :: OSI Approved :: MIT License",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Scientific/Engineering :: Physics",

  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
]


[project.urls]
Homepage = "https://github.com/egidioln/QuaTorch/"
Documentation = "https://egidioln.github.io/QuaTorch/"
Repository = "https://github.com/egidioln/QuaTorch.git"
Issues = "https://github.com/egidioln/QuaTorch/issues"
# Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"


[dependency-groups]
dev = [
    "furo",
    "matplotlib",
    "myst-nb",
    "myst-parser",
    "numpy",
    "pytest",
    "pytest-benchmark",
    "pytest-cov",
    "ruff",
    "setuptools",
    "sphinx",
    "sphinx-autobuild",
]


[build-system]
requires = ["uv_build >= 0.8.17, <0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["test"]
# Optional: set python_files pattern to include test files under unit_tests
python_files = ["test_*.py"]
addopts = "--cov=quatorch --cov-report xml:coverage.xml --cov-report html:htmlcov --cov-report json --benchmark-json benchmark_output.json"

[tool.coverage.report]
exclude_also = [
    'raise ValueError',
    'raise TypeError'
]

[project.optional-dependencies]
cu128 = [
  "torch",
]
cpu = [
  "torch",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch", extra = "cu128" },
  { index = "pytorch-cpu", extra = "cpu" },
]


[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true