# This runs a linter to check the code style (ruff)

name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: ruff
      env:
        VIRTUAL_ENV: '.venv'
      run: |
        uvx ruff format --diff .


