# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  UV_TORCH_BACKEND: cpu

jobs:
  test:
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Prepare enviromnment
      run: |
        python -m pip install uv
        uv python pin ${{ matrix.python-version }}
        uv venv .venv 
        source .venv/bin/activate
        uv sync

        

    - uses: yezz123/setup-uv@v4
      with:
        uv-venv: "test_env"
    - name: Install QuatTorch in editable mode
      run: uv pip install -e .
    - name: Run tests
      run: pytest test
      
