# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  test:
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Run Tests
      env:
        VIRTUAL_ENV: '.venv'
      run: |
        uv venv .venv
        uv python pin ${{ matrix.python-version }}
        uvx --with=.[cpu] pytest

    - name: Install QuatTorch in editable mode
      run: uv pip install -e .
    - name: Run tests
      run: pytest test
      
