# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  test:
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Run Tests
      env:
        VIRTUAL_ENV: '.venv'
      run: |
        uv venv .venv
        uv python pin ${{ matrix.python-version }}
        uv run --with=.[cpu] pytest
        git restore .python-version

      

    - name: Update Coverage Badge
      # GitHub actions: default branch variable
      # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      run: |
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages
        mkdir -p badges
        uvx coverage-badge -o ./badges/coverage.svg -f
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./badges/coverage.svg
        git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
        git push origin gh-pages
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        # PERSONAL_ACCESS_TOKEN is a PAT created by the user with repo permissions
        # and added to the repository secrets
        # https://docs.github.com/en/actions/security-guides/encrypted-secrets
        # https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
        # Note: GITHUB_TOKEN does not work for pushing to gh-pages branch
        # https://github.community/t/pushing-to-gh-pages-branch-with-github-token-fails-with-403/179000


    - name: 'Upload Coverage HTML'
      uses: actions/upload-artifact@v4
      with:
        name: coverage_html
        path: htmlcov/
        retention-days: 7
